sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t jenkins .
  - docker run -d -p 8080:8080 jenkins
  - docker ps -a

script:
  - sleep 80
  - curl http://127.0.0.1:8080
